# Generated by Django 4.2.27 on 2025-12-19 00:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, verbose_name='Nombre del Producto')),
                ('url', models.URLField(unique=True, verbose_name='URL del Producto')),
                ('target_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio Objetivo')),
                ('current_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Precio Actual')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
            ],
        ),
        migrations.CreateModel(
            name='PriceHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('captured_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio Capturado')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Captura')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='products.product')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
