# Generated by Django 4.2.27 on 2025-12-19 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='url',
            field=models.URLField(max_length=500, unique=True, verbose_name='URL del Producto'),
        ),
    ]
