# Generated by Django 4.2.27 on 2025-12-19 05:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0002_alter_product_url'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pricehistory',
            options={'ordering': ['-timestamp'], 'verbose_name': 'Historial de Precio', 'verbose_name_plural': 'Historiales de Precios'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['-created_at'], 'verbose_name': 'Producto', 'verbose_name_plural': 'Productos'},
        ),
        migrations.AddField(
            model_name='product',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='products', to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pricehistory',
            name='captured_price',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='pricehistory',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='current_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Precio Actual'),
        ),
        migrations.AlterField(
            model_name='product',
            name='target_price',
            field=models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Precio Objetivo'),
        ),
        migrations.AlterField(
            model_name='product',
            name='url',
            field=models.URLField(max_length=1000, verbose_name='URL del Producto'),
        ),
    ]
